export default [
  { heading: "Getting Started" },
  { path: "/index", text: "Overview" },
  { path: "/concepts", text: "Concepts" },
  null,
  { heading: "Tutorials" },
  { path: "/tutorial", text: "Basic" },
  null,
  { heading: "Editor" },
  { path: "/layout", text: "Layout" },
  { path: "/layers", text: "Layers" },
  { path: "/data", text: "Data" },
  null,
  { heading: "Playtesting" },
  { path: "/interface", text: "Interface" },
  { path: "/multiplayer", text: "Multiplayer" },
  null,
  { heading: "Automation" },
  { path: "/properties", text: "Properties" },
  { path: "/behaviors", text: "Behaviors" },
  { path: "/traits", text: "Traits" },
  { path: "/attributes", text: "Turn Orders" },
];
